spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    druid:
      maxActive: 20
      initialSize: 5
      maxWait: 60000
      minIdle: 5
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      validationQuery: SELECT 1 FROM DUAL
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      filters: stat,wall,slf4j
      maxPoolPreparedStatementPerConnectionSize: -1
    url: jdbc:mysql://localhost:3306/study?createDatabaseIfNotExist=true&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;autoReconnect=true&amp;zeroDateTimeBehavior=convertToNull
logging:
  level:
    org.springframework: INFO
    org.chaoliu1995.assistant.mapper: DEBUG
    org.chaoliu1995.assistant: INFO
  file: study-assistant.log
  path: /
server:
  port: 8085

CLIENT_IVV: 1102030405060708
CLIENT_SKEY: 1234567891234567
SERVER_IV: abcd123e456abdc9
SERVER_CRYPT_KEY: 8ig*lpk$=Fang5@P
appId: wx2396cb7893c2f132
appSecret: c9e08f8f46b9838aed6497f361df8a58
audioPath: D:\\MyFile\\English\\